### ISSUE TITLE
Instance

### ISSUE THREAD

**Issue by saeedkargosha** [pusher/pusher-platform-swift#43]
### Environment

* **PusherPlatform version:**0.7.1
* **Xcode version:**10.1
* **Swift version:**4.2
* **Platform(s) running PusherPlatform:**iOS

TestLogger: URLSession generalRequestURLSession became invalid
TestLogger: URLSession subscriptionURLSession became invalid
TestLogger: URLSession uploadURLSession became invalid
TestLogger: URLSession downloadURLSession became invalid

----

CC @pusher/sigsdk

**Comment by OliverPearmain-Pusher** [comment]
I don't believe there's sufficient detail here for us to address this issue.  Also since we haven't heard anything further in some time I am going to close this issue. 

Please re-open with more details if this is still an issue on the latest version.

Dedicated support is always available at https://support.pusher.com and support@pusher.com.
